#!/bin/bash
# Extract symbols for the graceloader's dynamic app loading system.
#
# This script produces two outputs:
#
# 1. main/exported_symbols.ld — EXTERN() directives for symbols from component
#    archives that aren't already in the ELF. These prevent --gc-sections from
#    stripping symbols that only apps reference. Uses a linker script to avoid
#    command-line length limits.
#
# 2. main/symbol_export/all — the complete symbol list for kbelf tables and
#    the fakelib. This is extracted from the final ELF AFTER the second build
#    (which includes the EXTERN'd symbols), so it only contains symbols that
#    actually link successfully. This avoids weak references in kbelf_lib_all.c
#    pulling in archive object files with unsatisfied transitive dependencies.
#
# All output files are sorted alphabetically for minimal diffs.
#
# Usage:
#   extract-symbols.sh              — generate exported_symbols.ld only
#   extract-symbols.sh --all        — generate both .ld and symbol_export/all
#
# Prerequisites: the graceloader must be built first (make build).

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

DEVICE="${DEVICE:-tanmatsu}"
BUILD_DIR="$PROJECT_DIR/build/$DEVICE"
SYMBOL_LIST="$PROJECT_DIR/main/symbol_export/all"
LD_FILE="$PROJECT_DIR/main/exported_symbols.ld"

GENERATE_ALL=false
if [ "${1:-}" = "--all" ]; then
    GENERATE_ALL=true
fi

# Component libraries whose symbols should be force-included for apps.
# Only list high-level app-facing APIs here. Low-level components
# (freertos, heap, hal, esp_driver_*, etc.) are already linked into
# the ELF naturally and their symbols are captured from the ELF
# extraction — no EXTERN forcing needed.
#
# Adding too many components here bloats the binary (kbelf symbol table
# + forced archive objects). The 2MB partition is the hard limit.
COMPONENTS=(
    badgeteam__badge-bsp
    robotman2412__pax-gfx
    nicolaielectronics__tanmatsu_coprocessor
    nvs_flash
)

# Find nm from the IDF toolchain
IDF_TOOLS_PATH="${IDF_TOOLS_PATH:-$PROJECT_DIR/esp-idf-tools}"
NM="$(find "$IDF_TOOLS_PATH" -name "riscv32-esp-elf-nm" -type f | head -1)"

if [ -z "$NM" ]; then
    echo "ERROR: Could not find riscv32-esp-elf-nm"
    echo "Make sure IDF_TOOLS_PATH is set or esp-idf-tools exists"
    exit 1
fi

if [ ! -d "$BUILD_DIR/esp-idf" ]; then
    echo "ERROR: Build directory not found at $BUILD_DIR"
    echo "Build the graceloader first: make build"
    exit 1
fi

ELF="$BUILD_DIR/application.elf"

# --- Generate exported_symbols.ld (always) ---
echo "Extracting symbols for exported_symbols.ld..."
echo "Using nm: $NM"

ELF_SYMS=$(mktemp)
ARCHIVE_SYMS=$(mktemp)

if [ -f "$ELF" ]; then
    echo "  Extracting from: application.elf"
    "$NM" -g --defined-only "$ELF" | awk '{print $3}' | grep '^[A-Za-z_][A-Za-z0-9_]*$' | sort -u > "$ELF_SYMS"
    echo "  $(wc -l < "$ELF_SYMS") symbols from ELF"
else
    echo "  WARNING: application.elf not found"
    touch "$ELF_SYMS"
fi

found=0
missing=0
for comp in "${COMPONENTS[@]}"; do
    archive="$BUILD_DIR/esp-idf/$comp/lib${comp}.a"
    if [ -f "$archive" ]; then
        echo "  Extracting from: $comp"
        "$NM" -g --defined-only "$archive" | awk '{print $3}' >> "$ARCHIVE_SYMS"
        found=$((found + 1))
    else
        echo "  WARNING: $comp not found (skipping)"
        missing=$((missing + 1))
    fi
done

sort -u "$ARCHIVE_SYMS" | grep -v '^$' > "${ARCHIVE_SYMS}.sorted"
mv "${ARCHIVE_SYMS}.sorted" "$ARCHIVE_SYMS"
echo "  $(wc -l < "$ARCHIVE_SYMS") symbols from archives ($found found, $missing missing)"

# EXTERN only symbols from archives that are NOT already in the ELF.
# This avoids multiple-definition errors from symbols in more than one archive.
EXTERN_SYMS=$(mktemp)
comm -23 "$ARCHIVE_SYMS" "$ELF_SYMS" > "$EXTERN_SYMS"
extern_count=$(wc -l < "$EXTERN_SYMS")

echo "Generating main/exported_symbols.ld..."
{
    echo "/* AUTO-GENERATED by tools/extract-symbols.sh -- do not edit */"
    echo "/* EXTERN() prevents --gc-sections from stripping symbols only used by apps */"
    echo "/* Only archive-only symbols are listed; ELF symbols are already linked */"
    while IFS= read -r sym; do
        [ -n "$sym" ] && echo "EXTERN($sym)"
    done < "$EXTERN_SYMS"
} > "$LD_FILE"

echo "Wrote $extern_count EXTERN() directives to main/exported_symbols.ld"

rm -f "$ARCHIVE_SYMS" "$EXTERN_SYMS"

# --- Generate symbol_export/all from ELF (only with --all) ---
if [ "$GENERATE_ALL" = true ]; then
    if [ ! -f "$ELF" ]; then
        echo "ERROR: application.elf not found for --all"
        rm -f "$ELF_SYMS"
        exit 1
    fi
    echo ""
    echo "Generating main/symbol_export/all from ELF..."
    # Re-extract from current ELF (which now includes EXTERN'd symbols).
    # Filter to valid C identifiers only (letters, digits, underscores).
    # This excludes compiler internals like DW.ref.* that can't be used
    # as variable names in the kbelf symbol table.
    "$NM" -g --defined-only "$ELF" | awk '{print $3}' | grep '^[A-Za-z_][A-Za-z0-9_]*$' | sort -u > "$SYMBOL_LIST"
    count=$(wc -l < "$SYMBOL_LIST")
    echo "Wrote $count symbols to main/symbol_export/all"
fi

rm -f "$ELF_SYMS"
